### ISSUE TITLE
feature: Model Performance plot

### ISSUE THREAD

**Issue by hbaniecki** [ModelOriented/Arena#3]
Usually the analysis of predictive models starts from evaluating [Model Performance](https://pbiecek.github.io/ema/modelPerformance.html). Sometimes there might be no point in explaining weak models; othertimes there might be no point in comparing multiple models without knowing their performance. It would be neat to have a [model_performance](https://modeloriented.github.io/DALEX/reference/model_performance.html) plot of some sort and/or be able to see tables like this: 
![image](https://user-images.githubusercontent.com/32574004/79155022-c9c4aa00-7dd0-11ea-8a9b-a22987678db7.png)

**Comment by piotrpiatyszek** [comment]
I'm implementing model performance plots right now. Take a look at the sessions below. If you have any suggestions about them or propositions for different charts, please let me know. Besides, I'm going to add a funnel plot.

Multiclass Classification: [link](https://arena.drwhy.ai/branch/dev/?session=https://gist.githubusercontent.com/piotrpiatyszek/5b9a2d866d73bb30a36c8182b4bb56c0/raw/cda7bc996d69608810f69a2e79194a2b46928049/session.json)
Regression: [link](https://arena.drwhy.ai/branch/dev/?session=https://gist.githubusercontent.com/piotrpiatyszek/341120a6a493b674d12103cf6c92d40c/raw/8cce3d5db3b8ce2f5a6a90c43081cdf5e02c9bf1/session.json)
